### ISSUE TITLE
Truncate long results

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_unittest#14]
In the tink_sql tests equality between very long strings is tested. The results become hard to read because the full string gets printed. Maybe those should be truncate? Or not printed if the test is successful?

**Comment by kevinresol** [comment]
you can customize the description by specifying the second parameter:

```haxe
assert(longString == 'longggggggstring', 'compare long string');
```

**Comment by benmerckx** [comment]
Thanks, that works!
