### ISSUE TITLE
Means to test for compilation/non-compilation in tests

### ISSUE THREAD

**Issue by thomasjwebb** [haxetink/tink_unittest#24]
It would be handy to have some means of ensuring that something compiles or doesn't compile in a test. Let's say I have a macro for validating my classes and I want to ensure that it _does not_ compile:

```haxe
class UnreasonableChecker {
    macro static public function build():Array<haxe.macro.Field> {
        var fields = Context.getBuildFields();
        for (field in fields) {
            if (field.name.startsWith('x') {
                Context.error('I HaTe vAriAblEs wHaT stARt WitH X', Context.currentPos());
            }
        }
        return fields
    }
}
```

```haxe
@:build(UnreasonableChecker.build())
class NaughtyClass {
    private var x:Int;
    private var y:Int;
}
```

Could I in the context of a unittest ensure that this doesn't succeed in building?

**Comment by kevinresol** [comment]
I guess the most straightforward way is to spawn a child process that runs haxe and check the output.

**Comment by back2dos** [comment]
Works now. Please note though that in the case of build macros you must not import or otherwise reference the type itself, as that makes the error uncatchable. You can use wildcard imports if you don't want the fully qualified path in the test.
