### ISSUE TITLE
How to only print failures info?

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_unittest#27]
How to only print Failures info?

     1717 Assertions   1715 Success   2 Failures   0 Error

It's too difficult to find out Failures info in output logs.

Is possible only to print failure information?

**Comment by kevinresol** [comment]
Yeah you can implement a custom Reporter

**Comment by back2dos** [comment]
There's actually a compact reporter here that you can use: https://github.com/haxetink/tink_testrunner/blob/master/src/tink/testrunner/Reporter.hx#L258
