### ISSUE TITLE
Run same test with different inputs

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_unittest#4]
```haxe
@:describe("GDC")
  @:case(32, 24, 8)
  @:case(42, 39, 3)
function testGdc(a:Int, b:Int, expected:Int) {
  return assert(gdc(a, b) == expected);
}
```

Or to use it for [tests we already have](https://github.com/haxetink/tink_url/blob/master/tests/TestHost.hx#L26):

```haxe
@:describe
  @:case('http://example.com,foo.com/foo/bar', ['example.com', 'foo.com'])
  @:case('http://example.com:80,foo.com:81/foo/bar', ['example.com:80', 'foo.com:81'])
function testMultiIpv4(url:Url, hosts:Array<String>) {
  return 
    assert(url.host, hosts[0])
      .concat([for (i in 0...hosts.length) 
         assert(hosts[i] == url.hosts[i])
      ]);
}
```

Not sure about the particular syntax. Maybe it should even be part of the `@:describe`?

```haxe
@:describe("multi host urls")
@:describe("  without port" ('http://example.com,foo.com/foo/bar', ['example.com', 'foo.com']))
@:describe("  with port" ('http://example.com:80,foo.com:81/foo/bar', ['example.com:80', 'foo.com:81'])
```

Or something like that ... the above would probably unnecessarily complicate treatment of `@:describe`. But some variation of this might do the trick, e.g  `@:case("description" (arg1, ... argN)) | @:case(arg1, ... argN)`.

The thing is, we have many tests where we're basically doing the same thing with just many different inputs. It would help us not only to separate the data and the actual test, but also avoid multiple asserts, which are still a little awkward as seen above.

**Comment by kevinresol** [comment]
I chose `@:variant` to distinguish from what "case" mean internally.
The "ECall with string" syxtax is quite unusual, but works :smile:

Closed by dc25617ff980ca53026c20483776ab93fb98c798
